# Builda config file
# This file is used to set up your 'builda' commands. Visit https://www.builda.app/setup for more information.

app:
  name: what's in the box
  outputDirectory: .
commands:
  component:
    type: scaffold
    outputDirectory: ./components
    scaffoldUrl: https://github.com/st-elmos-fire/scaffolds/tree/master/components/foxys-own
