import type { Metadata } from "next";
import { Archivo, Archivo_Black, Archivo_Narrow } from "next/font/google";
import StoreProvider from "./store-provider";
import '@theme/index.scss';

// Import components
import Masthead from "@components/masthead";

const ArchivoFont = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

const ArchivoBlackFont = Archivo_Black({
  variable: "--font-archivo-black",
  subsets: ["latin"],
  weight: "400",
});

const ArchivoNarrowFont = Archivo_Narrow({
  variable: "--font-archivo-narrow",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ArchivoFont.variable} ${ArchivoBlackFont.variable} ${ArchivoNarrowFont.variable}`}>
        <StoreProvider>
          <Masthead />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
