/**THIS FILE IS AUTOGENERATED, DO NOT EDIT**/
import { IconGallery, IconItem } from '@storybook/blocks';
import { Icon } from './index';
const Gallery = () => (
  <IconGallery>
    <IconItem name="Add">
      <Icon use="add" />
    </IconItem>

    <IconItem name="Address">
      <Icon use="address" />
    </IconItem>

    <IconItem name="AppLogo">
      <Icon use="applogo" />
    </IconItem>

    <IconItem name="Arrow">
      <Icon use="arrow" />
    </IconItem>

    <IconItem name="Barcode">
      <Icon use="barcode" />
    </IconItem>

    <IconItem name="Briefcase">
      <Icon use="briefcase" />
    </IconItem>

    <IconItem name="Camera">
      <Icon use="camera" />
    </IconItem>

    <IconItem name="Chevron">
      <Icon use="chevron" />
    </IconItem>

    <IconItem name="Clipboard">
      <Icon use="clipboard" />
    </IconItem>

    <IconItem name="Close">
      <Icon use="close" />
    </IconItem>

    <IconItem name="Delete">
      <Icon use="delete" />
    </IconItem>

    <IconItem name="Denied">
      <Icon use="denied" />
    </IconItem>

    <IconItem name="DocDownload">
      <Icon use="docdownload" />
    </IconItem>

    <IconItem name="Download">
      <Icon use="download" />
    </IconItem>

    <IconItem name="Edit">
      <Icon use="edit" />
    </IconItem>

    <IconItem name="Email">
      <Icon use="email" />
    </IconItem>

    <IconItem name="Error">
      <Icon use="error" />
    </IconItem>

    <IconItem name="Eye">
      <Icon use="eye" />
    </IconItem>

    <IconItem name="Facebook">
      <Icon use="facebook" />
    </IconItem>

    <IconItem name="Filter">
      <Icon use="filter" />
    </IconItem>

    <IconItem name="Floorplan">
      <Icon use="floorplan" />
    </IconItem>

    <IconItem name="HeartFilled">
      <Icon use="heartfilled" />
    </IconItem>

    <IconItem name="Heart">
      <Icon use="heart" />
    </IconItem>

    <IconItem name="Help">
      <Icon use="help" />
    </IconItem>

    <IconItem name="House">
      <Icon use="house" />
    </IconItem>

    <IconItem name="Image">
      <Icon use="image" />
    </IconItem>

    <IconItem name="Info">
      <Icon use="info" />
    </IconItem>

    <IconItem name="Instagram">
      <Icon use="instagram" />
    </IconItem>

    <IconItem name="LinkedIn">
      <Icon use="linkedin" />
    </IconItem>

    <IconItem name="Logout">
      <Icon use="logout" />
    </IconItem>

    <IconItem name="Map">
      <Icon use="map" />
    </IconItem>

    <IconItem name="Minus">
      <Icon use="minus" />
    </IconItem>

    <IconItem name="Moon">
      <Icon use="moon" />
    </IconItem>

    <IconItem name="Phone">
      <Icon use="phone" />
    </IconItem>

    <IconItem name="Pin">
      <Icon use="pin" />
    </IconItem>

    <IconItem name="Plus">
      <Icon use="plus" />
    </IconItem>

    <IconItem name="Refresh">
      <Icon use="refresh" />
    </IconItem>

    <IconItem name="Search">
      <Icon use="search" />
    </IconItem>

    <IconItem name="Share">
      <Icon use="share" />
    </IconItem>

    <IconItem name="Signpost">
      <Icon use="signpost" />
    </IconItem>

    <IconItem name="SortAsc">
      <Icon use="sortasc" />
    </IconItem>

    <IconItem name="SortDesc">
      <Icon use="sortdesc" />
    </IconItem>

    <IconItem name="Star">
      <Icon use="star" />
    </IconItem>

    <IconItem name="Success">
      <Icon use="success" />
    </IconItem>

    <IconItem name="Sun">
      <Icon use="sun" />
    </IconItem>

    <IconItem name="Tag">
      <Icon use="tag" />
    </IconItem>

    <IconItem name="Upload">
      <Icon use="upload" />
    </IconItem>

    <IconItem name="Users">
      <Icon use="users" />
    </IconItem>

    <IconItem name="Warning">
      <Icon use="warning" />
    </IconItem>
  </IconGallery>
);
export default Gallery;
