"""Rename cognito_id to auth_id

Revision ID: 32d2f21d7565
Revises: 646932f6e61b
Create Date: 2025-02-13 16:20:25.660262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d2f21d7565'
down_revision: Union[str, None] = '646932f6e61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_id', sa.String(), nullable=False))
    op.drop_constraint('users_cognito_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['auth_id'])
    op.drop_column('users', 'cognito_id')
    op.drop_column('users', 'staff_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('staff_role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('cognito_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_cognito_id_key', 'users', ['cognito_id'])
    op.drop_column('users', 'auth_id')
    # ### end Alembic commands ###
