"""Adds space_user join table

Revision ID: 4b0083c023f4
Revises: 2c6dbfd575ce
Create Date: 2025-02-09 14:25:34.242778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0083c023f4'
down_revision: Union[str, None] = '2c6dbfd575ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
